version: '3.9'

services:
  backend:
    image: myorg/backend:latest # Reference the pre-built cloud image
    environment:
      DATABASE_URL: mysql://root:whalehello@db:3306/mysql
      RUST_BACKTRACE: full
    ports:
      - 8080:8080
    restart: unless-stopped
    runtime: io.containerd.wasmedge.v1
    depends_on:
      - db

  db:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: whalehello
    ports:
      - "3306:3306"

  frontend:
    image: nginx:alpine
    ports:
      - 8090:80
    volumes:
      - ./frontend:/usr/share/nginx/html

networks:
  default:
    name: my_app_network